grappelli/urls.py
# coding: utf-8

# DJANGO IMPORTS
from django.conf.urls import patterns, url

# GRAPPELLI IMPORTS
from .views.related import RelatedLookup, M2MLookup, AutocompleteLookup
from .views.switch import switch_user


urlpatterns = patterns(
    '',

    # FOREIGNKEY & GENERIC LOOKUP
    url(r'^lookup/related/$', RelatedLookup.as_view(), name="grp_related_lookup"),
    url(r'^lookup/m2m/$', M2MLookup.as_view(), name="grp_m2m_lookup"),
    url(r'^lookup/autocomplete/$', AutocompleteLookup.as_view(), name="grp_autocomplete_lookup"),

    # SWITCH USER
    url(r'^switch/user/(?P<object_id>\d+)/$', switch_user, name="grp_switch_user"),

    # GRAPPELLI DOM DOCUMENTATION
    # url(r'^grp-doc/change-form/', TemplateView.as_view(template_name='grp_doc/change_form.html'), name="grp_doc_change_form"),
    # url(r'^grp-doc/change-list/', TemplateView.as_view(template_name='grp_doc/change_list.html'), name="grp_doc_change_list"),
    # url(r'^grp-doc/admin-index/', TemplateView.as_view(template_name='grp_doc/admin_index.html'), name="grp_doc_admin_index"),

    # url(r'^grp-doc/tables/', TemplateView.as_view(template_name='grp_doc/tables.html'), name="grp_doc_tables"),

    # url(r'^grp-doc/pagination/', TemplateView.as_view(template_name='grp_doc/pagination.html'), name="grp_doc_pagination"),
    # url(r'^grp-doc/search-form/', TemplateView.as_view(template_name='grp_doc/search_form.html'), name="grp_doc_search_form"),
    # url(r'^grp-doc/filter/', TemplateView.as_view(template_name='grp_doc/filter.html'), name="grp_doc_filter"),
    # url(r'^grp-doc/date-hierarchy/', TemplateView.as_view(template_name='grp_doc/date_hierarchy.html'), name="grp_doc_date_hierarchy"),

    # url(r'^grp-doc/fieldsets/', TemplateView.as_view(template_name='grp_doc/fieldsets.html'), name="grp_doc_fieldsets"),
    # url(r'^grp-doc/errors/', TemplateView.as_view(template_name='grp_doc/errors.html'), name="grp_doc_errors"),
    # url(r'^grp-doc/form-fields/', TemplateView.as_view(template_name='grp_doc/form_fields.html'), name="grp_doc_form_fields"),
    # url(r'^grp-doc/submit-rows/', TemplateView.as_view(template_name='grp_doc/submit_rows.html'), name="grp_doc_submit_rows"),

    # url(r'^grp-doc/modules/', TemplateView.as_view(template_name='grp_doc/modules.html'), name="grp_doc_modules"),
    # url(r'^grp-doc/groups/', TemplateView.as_view(template_name='grp_doc/groups.html'), name="grp_doc_groups"),

    # url(r'^grp-doc/navigation/', TemplateView.as_view(template_name='grp_doc/navigation.html'), name="grp_doc_navigation"),
    # url(r'^grp-doc/context-navigation/', TemplateView.as_view(template_name='grp_doc/context_navigation.html'), name="grp_doc_context_navigation"),

    # url(r'^grp-doc/basic-page-structure/', TemplateView.as_view(template_name='grp_doc/basic_page_structure.html'), name="grp_doc_basic_page_structure"),

    # url(r'^grp-doc/tools/', TemplateView.as_view(template_name='grp_doc/tools.html'), name="grp_doc_tools"),
    # url(r'^grp-doc/object-tools/', TemplateView.as_view(template_name='grp_doc/object_tools.html'), name="grp_doc_object_tools"),

    # url(r'^grp-doc/mueller-grid-system-tests/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_tests.html'), name="grp_doc_mueller_grid_system_tests"),
    # url(r'^grp-doc/mueller-grid-system/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system.html'), name="grp_doc_mueller_grid_system"),
    # url(r'^grp-doc/mueller-grid-system-layouts/', TemplateView.as_view(template_name='grp_doc/mueller_grid_system_layouts.html'), name="grp_doc_mueller_grid_system_layouts"),

    # url(r'^grp-doc', TemplateView.as_view(template_name='grp_doc/index.html'), name="grp_doc"),

)

t3/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    #url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('threefeatures.urls'), name='anasayfa'),
]

from django.conf import settings
if settings.DEBUG:
    urlpatterns.append(url(r"^media/(?P<path>.*)$", "django.views.static.serve", {"document_root":settings.MEDIA_ROOT}))

threefeatures/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *
admin.autodiscover()

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="iskelet.html"),  name='anasayfa'),
    url(r'^mekanlar/$', MekanFiltrele, name='Mekan_Arama'),
    url(r'^mekan_listesi/$', Mekan_Listele.as_view(), name='Mekan_Listesi'),
    url(r'^mekan_sil/(?P<pk>[0-9]+)$', Mekan_Sil.as_view(), name='Mekan_Sil'),
    url(r'^mekan_duzenle/(?P<pk>[0-9]+)$', Mekan_Duzenle.as_view(), name='Mekan_Duzenle'),
    url(r'^detaylar/(?P<mekanad>.+)/(?P<gelen_id>[0-9]+)/$', MekanDetay, name='Mekan_Detaylar'),
    url(r'^login/$', Kullanici_Giris, name='Kullanici_Giris'),
    url(r'^logout/$', Cikis, name='Kullanici_Cikis'),
    url(r'^reg/$', TemplateView.as_view(template_name='registration/register.html'), name='Kullanici_Kayit'),
    url(r'^reg_control/$', Kullanici_Kayit, name='Kayit_Kontrol'),
    url(r'^kayit/$', Mekan_Kayit.as_view(template_name='kayit.html'), name='Mekan_Kayit_Sayfasi'),
    url(r'^kadi_sorgula/$', Kayitli_Kullanici_Sorgula, name='Kayitli_Kullanici_Sorgula'),
    url(r'^parola_kontrol/$', Eski_Parola_Kontrol, name='Eski_Parola_Kontrol'),
    url(r'^update_us/$', Kullanici_Bilgileri_Guncelle.as_view(), name='Kullanici_Bilgileri_Guncelle'),
    url(r'^change_pass/$', Parola_Degistir, name='Parola_Degistir'),
    url(r'^alan_sorgula/$', Hizmet_Tip_Sorgula, name='Hizmet_Tip_Sorgula'),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^yildizla/', Begenilerim, name='yildizla'),
    url(r'^guvenlik_kodu/', Guvenlik_Kodu, name='gvk'),
    url(r'^abonelik/', Abone_Ol, name='abone'),
    url(r'^ucretsiz_talepler/', Ucretsiz_Hizmet_Talebi, name='ucretsiz_talepler'),

    url(r'^tara/(.+)$', Ad_Search, name='tara'),
    #url(r'^pub/$', MixWork, name='mix'),
    url(r'^trial/', MixWork, name='dene'),
    url(r'^adv/', Advenced_Work, name='adv'),
    url(r'^fora/', Listele.as_view(), name='obj'),
    url(r'^controls/', Calling, name='bibi'),
    url(r'^getting/', MyView.as_view(mesaj="oooooooo"), name='aag'),
    url(r'^yeniden/', Yeniden.as_view(), name='yeniden'),
    url(r'^yonlendir/', Yonlendirme.as_view(), name='yonlendir'),
    url(r'^sayfalama', sayfalama, name='sayfa'),
    url(r'^ekle', DbFunc, name='ekle'),
]

urlpatterns += staticfiles_urlpatterns()

threefeatures/models.py
# -*- coding: utf-8 -*-
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.utils import timezone
from django.db import models, IntegrityError
from django.contrib.auth.models import User


class UserProfil(models.Model):
    kullanici_id = models.CharField(max_length=20)
    kullanici_ip = models.GenericIPAddressField()

    def __str__(self):
        return self.kullanici_id + self.kullanici_ip

    class Meta:
        verbose_name = "Kullanıcı Profili"
        verbose_name_plural = "Kullanıcı Profilleri"

class Iller(models.Model):
    il_adi = models.CharField(max_length=40, help_text='İl Adını Girin')
    tarih = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return  self.il_adi



    class Meta:
        verbose_name = 'İl'
        verbose_name_plural = 'İller'

class Hizmetler(models.Model):
    hizmet_adi = models.CharField(max_length=80, help_text='Hizmet Adını Girin. Ör: Eğitim')

    def __str__(self):
        return  str(self.hizmet_adi)

    class Meta:
        verbose_name = 'Hizmet'
        verbose_name_plural = 'Hizmetler'

class HizmetTipleri(models.Model):
    hizmetler_adi = models.ForeignKey(Hizmetler)
    hizmet_tipi = models.CharField(max_length=60)

    def __str__(self):
        return  self.hizmet_tipi

    class Meta:
        verbose_name = 'Hizmet Tipi'
        verbose_name_plural = 'Hizmet Tipleri'

class Mekanlar(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=290, unique=False)
    hizmet_id = models.ForeignKey(Hizmetler, verbose_name='Hizmet Alanı')
    hizmet_tip_id = models.ForeignKey(HizmetTipleri, verbose_name='Hizmet Tipi')
    il_id = models.ForeignKey(Iller, verbose_name='İl')
    mekan_sahip_adi = models.CharField(max_length=75, verbose_name='Mekan Sahibi Adı')
    mekan_sahip_eposta = models.EmailField(verbose_name='E-Posta Adresi')
    mekan_foto =  models.ImageField(upload_to='assets/images/mekanlar/', verbose_name='Mekan Fotoğrafı')
    mekan_adi = models.CharField(max_length=120, verbose_name='Mekan Adı')
    mekan_tanitim = models.TextField(verbose_name='Mekan Tanıtım')
    mekan_web_site = models.URLField(verbose_name='Mekan Web Adresi', null=True, blank=True)
    mekan_telefon = models.CharField(max_length=14, verbose_name='Mekan Telefonu')
    mekan_fiyat = models.CharField(max_length=12, verbose_name='Mekan Minumum Hizmet Bedeli', null=True, blank=True, default='Minumum Bedel Belirtilmemiştir.')
    mekan_yetkisili = models.CharField(max_length=150, verbose_name='Mekan Yetkilisi')
    mekan_adres = models.TextField(verbose_name='Mekan Adresi')
    mekan_ozellik1 = models.CharField(max_length=20, verbose_name='Mekan Özellik#1')
    mekan_ozellik2 = models.CharField(max_length=20, verbose_name='Mekan Özellik#2')
    mekan_ozellik3 = models.CharField(max_length=20, verbose_name='Mekan Özellik#3')
    mekan_eklenme_tarih = models.DateTimeField(auto_now=True, verbose_name='Mekan Eklenme/Guncellenme Tarihi')
    mekan_ekleyen = models.CharField(max_length=100, verbose_name='Mekan Ekleyen Kullanıcı')
    mekan_onay = models.CharField(choices=(('0', '0'), ('1', '1')), max_length=1, default='0', verbose_name='Mekan Onay Durumu')

    def __str__(self):
        return self.mekan_adi

    def clean(self):
        if not self.mekan_sahip_eposta.endswith(end="@mynet.com"):
            raise ValidationError('Bu e-posta adresi geçersiz.')
        super(Mekanlar,self).clean()

    def save(self):
            """Auto-populate an empty slug field from the MyModel name and
            if it conflicts with an existing slug then append a number and try
            saving again.
            """
            import re
            from django.template.defaultfilters import slugify

            if not self.slug:
                self.slug = slugify(self.title)

            while True:
                try:
                    super(Mekanlar, self).save()
                # Assuming the IntegrityError is due to a slug fight
                except IntegrityError:
                    match_obj = re.match(r'^(.*)-(\d+)$', self.slug)
                    if match_obj:
                        next_int = int(match_obj.group(2)) + 1
                        self.slug = match_obj.group(1) + '-' + str(next_int)
                    else:
                        self.slug += '-2'
                else:
                    break



    class Meta:
        verbose_name = 'Mekan'
        verbose_name_plural = 'Mekanlar'


class Sectiklerimiz(models.Model):
    secim = (('4', '4'), ('5','5'))
    mekan_adi  = models.ForeignKey(Mekanlar)
    mekan_degerlendirme = models.TextField(max_length=120)
    mekan_yildiz = models.CharField(max_length=2, choices=secim)

    def __str__(self):
        return str(self.mekan_adi)

    def foto(self):
        return str(self.mekan_adi.mekan_foto)

    class Meta:
        verbose_name = 'Seçtiklerimiz'
        verbose_name_plural = 'Seçtiklerimiz'
        ordering = ['-mekan_adi']


class Begeniler(models.Model):
    kullanici_id = models.PositiveIntegerField(verbose_name='Kullanıcı')
    mekan_id = models.PositiveIntegerField(verbose_name='Mekan')
    yildiz = models.PositiveIntegerField(verbose_name='Yıldız Sayısı')

    def __str__(self):
        return str(self.kullanici_id)

    class Meta:
        verbose_name = 'Beğeni'
        verbose_name_plural = 'Beğeniler'


class Abonelik(models.Model):
    eposta = models.EmailField(verbose_name='Abone E-Posta Adresi')

    def __str__(self):
        return self.eposta

    class Meta:
        verbose_name="E-Posta Adresi"
        verbose_name_plural="E-Posta Adres"


class Ucretsiz_Hizmetler(models.Model):
    turler = (('0', 'Afiş'), ('1', 'Animasyon'), ('2', 'Intro'))
    tur  = models.CharField(choices=turler, max_length=20)
    foto_video = models.FileField(upload_to="ucretsizler/", verbose_name="Fotoğraf/Video")
    aciklama = models.CharField(max_length=150)
    ilgili_hizmet = models.ManyToManyField(HizmetTipleri)
    ilgili_hizmet_sure = models.DateTimeField(auto_now=False, auto_created=True, null=True, blank=True, verbose_name='Fırsat Süresi')


    def __str__(self):
        return self.tur

    def coklu_gosterim(self):
        return ', '.join([ other.hizmet_tipi for other in self.ilgili_hizmet.all() ])
    coklu_gosterim.short_description = 'Tavsiye Edilen Hizmet'
    coklu_gosterim.allow_tags = True

    class Meta:
        verbose_name="Ücretsiz Hizmet"
        verbose_name_plural="Ücretsiz Hizmetler"


class Ucretsiz_Hizmet_Talepleri(models.Model):
    sonuc= (
        ('0', ('Onaylanmamış')),
        ('1', ('Talep kabul edildi.')),
        ('2', ('Talep reddedildi.'))
    )
    uye_istek = models.CharField(max_length=50, verbose_name="Talep Eden Üye")
    talep_edilen_hizmet = models.CharField(max_length=20, verbose_name="Talep Edilen Hizmet")
    talep_tarih = models.DateTimeField(auto_now=True, verbose_name="Talep Tarihi")
    talep_sonuc= models.CharField(max_length=25, choices=sonuc, verbose_name="Talep Durumu")

    def __str__(self):
        return str(self.talep_tarih) + str(self.talep_tarih)

    class Meta:
        verbose_name="Ücretsiz Hizmet Talebi"
        verbose_name_plural="Ücretsiz Hizmet Talepleri"

threefeatures/forms.py
from django.forms import ModelForm
from django import forms
from .models import Mekanlar, Hizmetler
from django import forms


class BegeniForm(forms.ModelForm):
    class Meta:
        model = Mekanlar
        fields = ['mekan_fiyat', 'mekan_adi', 'mekan_web_site']

class FormYeni(forms.ModelForm):
    class Meta:
        model  = Hizmetler
        fields = ['hizmet_adi']

threefeatures/templates/auth.html
{% extends "iskelet.html" %}

{%  block guncelle_kadi %}

     <div class="alert alert-danger" role="alert"><span class="text-center">Geçersiz e-posta adresi yada kullanıcı adı girdiniz.</span></div>

{% endblock %}

threefeatures/templates/deneme.html
{% block analiz %}
<div class="container">
    <div class="row">
        <div class="well well-lg">
           {{ sonuclar.yazar }}
        </div>
    </div>
</div>

    <form action=""  method="post">
            {% csrf_token %}
                {{ out.as_table }}
                <input type="submit" value="Go">
    </form>

     <h1>Min: </h1>{{ min }}
     <h1>Ortalama : </h1>{{ avg }}
     <h1>Max : </h1>{{ max }}
    <h2>Aciklama : </h2> {{ cont }}
    <h2>ilk : </h2> {{ ilk }}
    <h2>deger : </h2>
    {% for i in degerler %}
    {{ i.mekan_fiyat }} <br>
    {% endfor %}


    <h1>farkli sorgulama</h1>
  <h2>  {% if pat|length > 100 %}
  aliveli
  {% else %}
  velideli
  {% endif %}
  </h2>


{% endblock %}

threefeatures/templates/listele.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{% for foo in veriler %}
{{ foo.mekan_fiyat }}
{% endfor %}

</body>
</html>

threefeatures/templates/mekan_listesi.html
{% extends "iskelet.html" %}
{% load static from staticfiles %}
{% block ucretsizler %}

{% endblock %}

{% block analiz %}

{% endblock %}

{%  if user.authenticated %}
{% block mekan_listesi %}

<div class="container margin-top-10">
    {% if request.POST %}
        {% if form.errors %}
    <div class="alert alert-danger" role="alert"><span class="text-center">Güncelleme İşlemi Gerçekleşmedi. <br> Form Bilgileri Geçersiz.</span></div>
        {% else %}
    <div class="alert alert-success" role="alert"><span class="text-center">Güncelleme İşlemi Gerçekleşti. <br> </span></div>
        {% endif %}
    {% endif %}
<div class="row well well-lg">
<table class="table table-condensed">
<h1 class="text-center text-shadow">KAYITLI MEKAN LİSTESİ</h1>
<p style="border-bottom: 2px dashed gray;"></p>
<tr style="text-transform: uppercase;">
  <td class="danger"><strong>Mekan Adı</strong></td>
  <td class="success"><strong>Hizmet Alanı</strong></td>
  <td class="warning"><strong>Hizmet Tipi</strong></td>
  <td class="danger"><strong>Mekan İli</strong></td>
  <td class="warning"><strong>Onay Durumu</strong></td>
  <td class="success"><strong>İşlem</strong></td>

</tr>
{% for mekan in mekan_listesi %}
  <tr>
  <td>{{ mekan.mekan_adi|capfirst }}</td>
  <td>{{ mekan.hizmet_id }}</td>
  <td>{{ mekan.hizmet_tip_id }}</td>
  <td>{{ mekan.il_id }}</td>
  <td>{% if mekan.mekan_onay == '0' %}
            <p class="icon-edit">Onaylanmamış</p>
      {% else %}
            <p>Onaylı</p>
      {% endif %}
</td>
<td>
      <!--
       Deleteview POST ile çalışıyor çünkü chrome siteler hızlı açılsın diye önceden linkleri getliyor. Eğer deleteview get ile çalışsaydı chrome bütün mekanları yanlışlıkla silerdi.
       Deletiview ayrıca silmek istiyormusun şeklinde bir soru sorar bunun için GET methodunu kullanman gerekli. eğer direk sileceksen POST kullanacaksın.
       -->
      <a class="btn btn-danger" style="margin: 5px;" href="{% url "Mekan_Sil" pk=mekan.pk %}">Sil</a>
      <a class="btn btn-warning" style="margin: 5px;" href="{% url "Mekan_Duzenle" pk=mekan.pk %}">Düzenle</a>
  </td>

</tr>
    {% endfor %}
</table>

    {% if sil %}

        <div class="container">
            <div class="row">
                <div class="well well-lg">
                    <p>{{ sil }} adlı kaydı silmek istediğine emin misin?</p>
                    <form action="" method="post">
                        {% csrf_token %}
                    <input  class="btn btn-success" type="submit" value="Evet"/>
                        <input  class="btn btn-danger" onclick="window.history.go(-1);" value="Hayır"/>
                    </form>

                </div>
            </div>
        </div>
    {% endif %}
    </div>

    {% if guncelle %}
        <div class="container_wrap">
        <div class="row">
        <div class="col-md-8 align-center well well-lg">
        <form action="" method="post" id="duzenle" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_table }}
            <br>
            <input type="submit" class="btn btn-success" value="Güncelle">
            <input class="btn btn-danger" value="İptal" onclick="window.history.go(-1);">
        </form>
            <br>
        </div>
        </div>
        </div>
    {% endif %}

    <script>
         $(function  () {

              var secilmis =   $("#id_hizmet_tip_id option[selected]").val();

              $("#id_hizmet_tip_id option").not("#id_hizmet_tip_id option:nth-of-type(" + secilmis + ")").remove();


                $("#id_hizmet_id").on("change", function  () {

                $("#id_hizmet_tip_id option").remove();

                var giden = $("#id_hizmet_id").val();

                $.post("{% url 'Hizmet_Tip_Sorgula' %}", {"veri":giden},
                   function(cevap)
                   {
                       for(i=0; i<cevap.length; i++) {
                           $("#id_hizmet_tip_id").append('<option value="' + cevap[i][0] +'">'  + cevap[i][1] + '</option>');
                       }

                   }, "json");
               })


            $(function () {
                  var i = $("#kadim");

                  if (i.length < 1) {
                            window.location.href = "{% url 'anasayfa' %}" ;
                  }
            })

        })

        $(function () {
            $("#duzenle input, select, textarea").addClass('form-control');
        })
    </script>
</div>

    <div class="container">

        <div class="living_box" >
            <div class="col-md-16 text-center" data-toggle="modal" data-target="#FirsatModal">
            <img src="{% static "images/firsat1.png" %}" width="128" height="128" class="text-center"> </div>
            <h2 class="text-center text-bold text-shadow text-info cursor-pointer" data-toggle="modal" data-target="#FirsatModal">Fırsat Ekle</h2>
            </div>



    </div>

    <div class="modal fade" id="FirsatModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Fırsat Ekle</h4>
      </div>
      <div class="modal-body">
        <form action="" method="post">
        {% csrf_token %}
            <div class="form-group">
            <label for="firsat_mekan_id" class="control-label">Mekan/Firma</label>
                <select name="firsat_mekan_id" id="firsat_mekan_id" class="form-control">
                   {% for mekan in mekan_listesi %}
                       <option>{{ mekan.mekan_adi|capfirst }}</option>
                    {% endfor %}
                </select>
          </div>
          <div class="form-group">
            <label for="firsat_foto" class="control-label">Fırsat Fotoğrafı:</label>
            <input type="file" class="form-control" id="firsat_foto" name="firsat_foto" accept="image/*">
          </div>
            <div class="form-group">
            <label for="firsat_baslangic" class="control-label">Fırsat Başlangıcı:</label>
            <input type="datetime-local" class="form-control" id="firsat_baslangic" name="firsat_baslangic">
            </div>
            <div class="form-group">
            <label for="firsat_bitis" class="control-label">Fırsat Bitiş:</label>
            <input type="datetime-local" class="form-control" id="firsat_bitis" name="firsat_bitis">
            </div>
            <div class="form-group">
            <label for="firsat_fiyat" class="control-label">Ürün/Hizmet Fiyatı:</label>
            <input type="text" class="form-control" id="firsat_fiyat" name="firsat_fiyat">
            </div>
        <div class="form-group">
            <label for="firsat_indirim_oran" class="control-label">İndirim Oranı:</label>
            <input type="text" class="form-control" id="firsat_indirim_oran" name="firsat_indirim_oran" maxlength="3" aria-valuemax="100">
            </div>

          <div class="form-group">
            <label for="firsat_aciklama" class="control-label">Fırsat Açıklama:</label>
            <textarea class="form-control" id="firsat_aciklama" name="firsat_aciklama" maxlength="150"></textarea>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Send message</button>
      </div>
     </form>
    </div>
  </div>
</div>
{% endblock %}
{% endif %}

threefeatures/templates/sayfalama.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
<ul>
{% for foo in veriler %}
        <li>{{ foo }}</li>
{% endfor %}

{% for sayi in aralik %}
    <a href="?s={{ sayi }}"> {{ sayi }} </a>
{% endfor %}


    <form action="" method="post">
    {% csrf_token %}
{% for foo in formlar %}
 {{ foo.label_tag }}
 {{ foo.help_text }}
    {{ foo }}
    {{ foo.html_name }}
   {% if formlar.errors %}
        {{ formlar.hizmet_adi.errors }}
   {% endif %}
     

{% endfor %}
        <input type="submit">
</form>

    <hr>


</ul>
</body>
</html>